In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, 4].values

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,3] = labelencoder_X.fit_transform(X[:,3])
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()
X = X[:,1:]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

import statsmodels.api as sm

X = np.append(arr= np.ones((50,1)), values= X, axis=1)

def backwardElimination(x, SL):
    numVars = len(x[0])
    temp = np.zeros((50,6)).astype(int)
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y,x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        adjR_before = regressor_OLS.rsquared_adj.astype(float)
        if maxVar>SL:
             for j in range(0, numVars-i):
                if(regressor_OLS.pvalues[j]==maxVar): 
                    temp[:,j] = x[:,j]
                    x = np.delete(x,j,1)
                    temp_regressor = sm.OLS(y,x).fit()
                    adjR_after = temp_regressor.rsquared_adj.astype(float)
                    if(adjR_before>=adjR_after):
                        x_rollback = np.hstack((x, temp[:, [0,j]]))
                        x_rollback = np.delete(x_rollback, j,1)
                        print(regressor_OLS.summary())
                        return x_rollback
                    else:
                        continue    
    regressor_OLS.summary()
    return x
SL = 0.05
X_opt = X[:, [0,1,2,3,4,5]]
X_Modeled = backwardElimination(X_opt, SL)

C:\Users\Vaish\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Vaish\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Fri, 07 Feb 2020   Prob (F-statistic):           2.16e-31
Time:                        20:59:45   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [3]:
X_Modeled.astype(int)

array([[     1, 165349, 471784],
       [     1, 162597, 443898],
       [     1, 153441, 407934],
       [     1, 144372, 383199],
       [     1, 142107, 366168],
       [     1, 131876, 362861],
       [     1, 134615, 127716],
       [     1, 130298, 323876],
       [     1, 120542, 311613],
       [     1, 123334, 304981],
       [     1, 101913, 229160],
       [     1, 100671, 249744],
       [     1,  93863, 249839],
       [     1,  91992, 252664],
       [     1, 119943, 256512],
       [     1, 114523, 261776],
       [     1,  78013, 264346],
       [     1,  94657, 282574],
       [     1,  91749, 294919],
       [     1,  86419,      0],
       [     1,  76253, 298664],
       [     1,  78389, 299737],
       [     1,  73994, 303319],
       [     1,  67532, 304768],
       [     1,  77044, 140574],
       [     1,  64664, 137962],
       [     1,  75328, 134050],
       [     1,  72107, 353183],
       [     1,  66051, 118148],
       [     1,  65605, 107138],
       [     1,  61994,  91131],
       [     1,  61136,  88218],
       [     1,  63408,  46085],
       [     1,  55493, 214634],
       [     1,  46426, 210797],
       [     1,  46014, 205517],
       [     1,  28663, 201126],
       [     1,  44069, 197029],
       [     1,  20229, 185265],
       [     1,  38558, 174999],
       [     1,  28754, 172795],
       [     1,  27892, 164470],
       [     1,  23640, 148001],
       [     1,  15505,  35534],
       [     1,  22177,  28334],
       [     1,   1000,   1903],
       [     1,   1315, 297114],
       [     1,      0,      0],
       [     1,    542,      0],
       [     1,      0,  45173]])

In [4]:
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_Modeled, y, test_size=0.2, random_state=0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [7]:
y_pred.astype(int)

array([102284, 133873, 134182,  73701, 180642, 114717,  68335,  97433,
       114580, 170343])

In [8]:
regressor.score(X_test, y_test)

0.9474386479910116