In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("dataset/Minimum Wage Data.csv", encoding = "latin")

In [3]:
df.to_csv("dataset/minimum_wage.csv", encoding="utf-8")

In [4]:
df.head()

,Year,State,Table_Data,Footnote,High.Value,Low.Value,CPI.Average,High.2018,Low.2018
0,1968,Alabama,...,NaN,0.00000,0.00000,34.783333,0.00,0.00
1,1968,Alaska,2.10,NaN,2.10000,2.10000,34.783333,15.12,15.12
2,1968,Arizona,18.72 - 26.40/wk(b),(b),0.66000,0.46800,34.783333,4.75,3.37
3,1968,Arkansas,1.25/day(b),(b),0.15625,0.15625,34.783333,1.12,1.12
4,1968,California,1.65(b),(b),1.65000,1.65000,34.783333,11.88,11.88

In [5]:
df = pd.read_csv("dataset/minimum_wage.csv")

In [6]:
gb = df.groupby("State")

In [7]:
gb.head()

,Unnamed: 0,Year,State,Table_Data,Footnote,High.Value,Low.Value,CPI.Average,High.2018,Low.2018
0,0,1968,Alabama,...,NaN,0.00000,0.00000,34.783333,0.00,0.00
1,1,1968,Alaska,2.10,NaN,2.10000,2.10000,34.783333,15.12,15.12
2,2,1968,Arizona,18.72 - 26.40/wk(b),(b),0.66000,0.46800,34.783333,4.75,3.37
3,3,1968,Arkansas,1.25/day(b),(b),0.15625,0.15625,34.783333,1.12,1.12
4,4,1968,California,1.65(b),(b),1.65000,1.65000,34.783333,11.88,11.88
...,...,...,...,...,...,...,...,...,...,...
270,270,1972,Virginia,...,NaN,0.00000,0.00000,41.816667,0.00,0.00
271,271,1972,Washington,1.60,NaN,1.60000,1.60000,41.816667,9.58,9.58
272,272,1972,West Virginia,1.20,NaN,1.20000,1.20000,41.816667,7.19,7.19
273,273,1972,Wisconsin,1.45 (b),(b),1.45000,1.45000,41.816667,8.68,8.68
274,274,1972,Wyoming,1.50,NaN,1.50000,1.50000,41.816667,8.98,8.98

In [8]:
gb.get_group("Alabama").set_index("Year").head()

,Unnamed: 0,State,Table_Data,Footnote,High.Value,Low.Value,CPI.Average,High.2018,Low.2018
Year,,,,,,,,,
1968,0,Alabama,...,NaN,0.0,0.0,34.783333,0.0,0.0
1969,55,Alabama,...,NaN,0.0,0.0,36.683333,0.0,0.0
1970,110,Alabama,...,NaN,0.0,0.0,38.825000,0.0,0.0
1971,165,Alabama,...,NaN,0.0,0.0,40.491667,0.0,0.0
1972,220,Alabama,...,NaN,0.0,0.0,41.816667,0.0,0.0

In [9]:
act_minimum_wage = pd.DataFrame()

In [10]:
for name, group in df.groupby("State"):
    if act_minimum_wage.empty:
        act_minimum_wage = group.set_index("Year")[["Low.2018"]].rename(columns={"Low.2018":name})
    else:
        act_minimum_wage = act_minimum_wage.join(group.set_index("Year")[["Low.2018"]].rename(columns={"Low.2018":name}))

In [11]:
act_minimum_wage.head(25)

,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Federal (FLSA),...,Tennessee,Texas,U.S. Virgin Islands,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
Year,,,,,,,,,,,,,,,,,,,,,
1968,0.0,15.12,3.37,1.12,11.88,7.20,10.08,9.00,9.00,8.28,...,0.0,0.00,NaN,7.20,10.08,0.00,11.52,7.20,9.00,8.64
1969,0.0,14.33,3.19,1.07,11.26,6.83,9.56,8.53,8.53,7.85,...,0.0,0.00,NaN,6.83,9.56,0.00,10.92,6.83,8.53,8.19
1970,0.0,13.54,3.02,7.09,10.64,6.45,10.32,8.06,10.32,8.38,...,0.0,0.00,NaN,6.45,10.32,0.00,10.32,6.45,8.38,8.38
1971,0.0,12.99,2.89,6.80,10.20,6.18,9.89,7.73,9.89,8.04,...,0.0,0.00,NaN,6.18,9.89,0.00,9.89,6.18,8.04,8.04
1972,0.0,12.57,2.80,7.19,9.88,5.99,11.08,9.58,9.58,9.58,...,0.0,8.38,NaN,7.19,9.58,0.00,9.58,7.19,8.68,8.98
1973,0.0,11.84,2.64,6.77,9.31,5.64,10.43,9.02,9.02,9.02,...,0.0,7.90,NaN,6.77,9.02,0.00,9.02,6.77,8.18,8.46
1974,0.0,10.66,2.38,6.09,8.38,5.08,9.39,8.13,8.13,8.13,...,0.0,7.11,NaN,6.09,8.13,0.00,8.13,6.09,7.36,7.62
1975,0.0,9.77,2.18,5.58,7.68,4.65,8.61,7.44,7.44,7.44,...,0.0,6.51,NaN,5.58,7.44,0.00,7.44,5.58,6.75,6.98
1976,0.0,12.32,0.00,8.36,8.80,4.40,9.72,8.80,9.90,9.68,...,0.0,6.16,NaN,6.82,10.12,8.80,9.68,8.80,9.24,7.04
1977,0.0,11.57,0.00,7.85,8.26,4.13,9.13,8.26,9.30,9.09,...,0.0,5.78,NaN,6.40,9.50,8.26,9.09,8.26,8.68,6.61
1978,0.0,10.75,0.00,7.29,7.68,3.84,8.48,7.68,8.64,8.44,...,0.0,5.37,NaN,5.95,8.83,7.68,8.44,7.68,8.06,6.14
1979,0.0,11.73,0.00,7.94,10.01,6.56,10.04,6.90,8.49,10.01,...,0.0,4.83,10.01,7.59,10.01,8.11,7.94,7.59,9.66,5.52
1980,0.0,10.94,0.00,7.75,8.81,5.77,9.48,6.08,7.60,9.42,...,0.0,4.25,9.42,7.14,9.42,7.14,6.99,6.68,9.12,4.86
1981,0.0,10.60,0.00,7.44,9.23,5.23,9.28,5.51,6.88,9.23,...,0.0,3.86,9.23,6.88,9.23,7.30,6.33,7.57,8.95,4.41
1982,0.0,9.99,0.00,7.01,8.69,4.93,8.74,5.19,6.49,8.69,...,0.0,3.63,8.69,6.49,8.69,6.88,5.97,7.14,8.43,4.15
1983,0.0,9.68,0.00,6.79,8.42,4.78,8.47,5.03,6.29,8.42,...,0.0,3.52,8.42,6.29,8.42,6.66,5.78,6.91,8.17,4.02
1984,0.0,9.28,0.00,6.51,8.07,4.58,8.12,4.82,6.03,8.07,...,0.0,3.37,8.07,6.03,8.07,6.39,5.54,6.63,7.83,3.86
1985,0.0,8.96,0.00,6.29,7.80,4.42,7.84,4.66,5.82,7.80,...,0.0,3.26,7.80,5.82,7.80,6.17,5.35,6.40,7.57,3.72
1986,0.0,8.80,0.00,6.17,7.65,4.34,7.70,4.57,5.71,7.65,...,0.0,3.20,7.65,5.71,7.65,6.05,5.25,6.28,7.42,3.66
1987,0.0,8.48,0.00,5.95,7.38,4.19,7.43,4.41,5.51,7.38,...,0.0,3.09,7.38,5.51,7.38,5.84,5.07,6.06,7.16,3.53
1988,0.0,8.15,0.00,6.88,7.09,6.35,7.94,7.09,7.41,7.09,...,0.0,7.09,7.09,5.29,7.52,5.61,4.87,7.09,7.09,3.39
1989,0.0,7.78,0.00,6.56,6.77,6.06,7.57,6.77,7.07,6.77,...,0.0,6.77,6.77,5.05,7.17,5.35,4.65,6.77,6.77,3.23
1990,0.0,7.38,0.00,6.23,6.42,5.75,7.19,6.42,6.71,6.42,...,0.0,6.42,6.42,4.79,6.80,5.08,4.41,6.42,6.42,3.07
1991,0.0,7.91,0.00,6.16,7.81,5.52,7.81,6.99,6.80,6.99,...,0.0,6.16,8.55,6.99,7.08,4.87,7.81,6.16,6.99,2.94
1992,0.0,8.48,0.00,6.51,7.58,5.35,7.62,7.58,6.96,7.58,...,0.0,5.98,8.30,7.58,7.58,6.51,7.58,6.78,6.78,2.86

In [12]:
act_minimum_wage.describe()

,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Federal (FLSA),...,Tennessee,Texas,U.S. Virgin Islands,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
count,50.0,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,...,50.0,50.000000,39.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,0.0,9.583800,2.316200,6.781600,8.632800,6.389800,8.823600,7.498800,8.343200,7.773200,...,0.0,5.541200,6.643590,6.836600,8.657400,5.897400,8.301800,7.166400,7.694200,5.149200
std,0.0,1.845176,3.474504,1.341223,1.187508,1.521052,1.023613,1.265436,1.476133,0.887354,...,0.0,2.202229,1.590176,0.819367,0.984647,2.726151,1.868613,0.793673,0.762675,1.998928
min,0.0,7.380000,0.000000,1.070000,6.420000,3.840000,6.820000,4.410000,5.510000,6.220000,...,0.0,0.000000,4.390000,4.790000,6.800000,0.000000,4.410000,5.580000,6.420000,2.260000
25%,0.0,8.252500,0.000000,6.522500,7.695000,5.072500,7.865000,7.015000,7.097500,7.172500,...,0.0,4.762500,5.105000,6.317500,7.800000,5.892500,7.227500,6.630000,7.107500,3.270000
50%,0.0,8.890000,0.000000,6.920000,8.670000,6.375000,9.075000,7.845000,8.510000,7.655000,...,0.0,6.070000,6.770000,6.930000,8.885000,6.855000,9.055000,7.075000,7.580000,5.445000
75%,0.0,10.492500,3.147500,7.290000,9.307500,7.677500,9.455000,8.327500,9.140000,8.242500,...,0.0,7.105000,7.830000,7.470000,9.372500,7.620000,9.672500,7.612500,8.145000,6.607500
max,0.0,15.120000,10.220000,8.680000,11.880000,9.500000,11.080000,9.580000,12.000000,10.010000,...,0.0,8.380000,10.010000,8.330000,10.320000,8.800000,11.520000,9.130000,9.660000,8.980000

In [13]:
act_minimum_wage.corr().head(10)

,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Federal (FLSA),...,Tennessee,Texas,U.S. Virgin Islands,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alaska,NaN,1.000000,0.018638,-0.377934,0.717653,-0.129332,0.680886,0.258997,0.321785,0.637679,...,NaN,-0.522472,0.277016,-0.020462,0.663558,-0.601640,0.411593,0.044814,0.702570,0.727932
Arizona,NaN,0.018638,1.000000,0.089395,0.498994,0.742527,0.458163,0.429836,0.590848,-0.049914,...,NaN,0.369900,-0.758607,0.439344,0.517960,0.047405,0.587975,0.584596,0.131588,0.346528
Arkansas,NaN,-0.377934,0.089395,1.000000,-0.234367,0.135749,0.047580,0.016125,0.266889,0.117245,...,NaN,0.503242,-0.204485,0.194680,0.087429,0.582192,-0.072343,0.420819,0.000470,-0.250592
California,NaN,0.717653,0.498994,-0.234367,1.000000,0.483313,0.876215,0.479197,0.596865,0.371966,...,NaN,-0.239533,-0.417782,0.392898,0.877922,-0.326364,0.754085,0.371765,0.584067,0.722617
Colorado,NaN,-0.129332,0.742527,0.135749,0.483313,1.000000,0.402020,0.566304,0.673371,-0.232035,...,NaN,0.350796,-0.791134,0.622330,0.448485,0.210271,0.612637,0.533623,0.011501,0.130053
Connecticut,NaN,0.680886,0.458163,0.047580,0.876215,0.402020,1.000000,0.552613,0.652488,0.487750,...,NaN,0.049405,-0.446165,0.302538,0.898469,-0.310705,0.715691,0.400099,0.585790,0.814971
Delaware,NaN,0.258997,0.429836,0.016125,0.479197,0.566304,0.552613,1.000000,0.796457,-0.009271,...,NaN,0.374150,-0.688552,0.501815,0.487378,-0.167700,0.830850,0.436045,0.071042,0.502713
District of Columbia,NaN,0.321785,0.590848,0.266889,0.596865,0.673371,0.652488,0.796457,1.000000,0.151129,...,NaN,0.251189,-0.693560,0.537581,0.718686,0.007414,0.798094,0.644477,0.267017,0.438793
Federal (FLSA),NaN,0.637679,-0.049914,0.117245,0.371966,-0.232035,0.487750,-0.009271,0.151129,1.000000,...,NaN,-0.183950,0.475240,0.221539,0.504419,-0.105622,0.075067,0.272645,0.870658,0.328639

In [14]:
issue_df = df[df["Low.2018"]==0]

In [15]:
issue_df.head()

,Unnamed: 0,Year,State,Table_Data,Footnote,High.Value,Low.Value,CPI.Average,High.2018,Low.2018
0,0,1968,Alabama,...,NaN,0.0,0.0,34.783333,0.0,0.0
10,10,1968,Florida,...,NaN,0.0,0.0,34.783333,0.0,0.0
11,11,1968,Georgia,...,NaN,0.0,0.0,34.783333,0.0,0.0
15,15,1968,Illinois,...,NaN,0.0,0.0,34.783333,0.0,0.0
17,17,1968,Iowa,...,NaN,0.0,0.0,34.783333,0.0,0.0

In [16]:
issue_df["State"].unique()

array(['Alabama', 'Florida', 'Georgia', 'Illinois', 'Iowa', 'Kansas',
       'Louisiana', 'Mississippi', 'Missouri', 'Montana',
       'South Carolina', 'Tennessee', 'Texas', 'Virginia', 'Arizona'],
      dtype=object)

In [18]:
minimum_wage_corr = act_minimum_wage.replace(0,np.NaN).dropna(axis=1).corr().head(25)

In [19]:
minimum_wage_corr

,Alaska,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Federal (FLSA),Guam,Hawaii,...,Pennsylvania,Puerto Rico,Rhode Island,South Dakota,Utah,Vermont,Washington,West Virginia,Wisconsin,Wyoming
Alaska,1.000000,-0.377934,0.717653,-0.129332,0.680886,0.258997,0.321785,0.637679,0.787915,0.672620,...,0.610814,-0.038118,0.652353,-0.326316,-0.020462,0.663558,0.411593,0.044814,0.702570,0.727932
Arkansas,-0.377934,1.000000,-0.234367,0.135749,0.047580,0.016125,0.266889,0.117245,0.039593,0.204801,...,0.159923,0.232186,0.003498,0.800116,0.194680,0.087429,-0.072343,0.420819,0.000470,-0.250592
California,0.717653,-0.234367,1.000000,0.483313,0.876215,0.479197,0.596865,0.371966,0.492052,0.519241,...,0.429061,0.512712,0.780916,-0.036787,0.392898,0.877922,0.754085,0.371765,0.584067,0.722617
Colorado,-0.129332,0.135749,0.483313,1.000000,0.402020,0.566304,0.673371,-0.232035,-0.192616,0.069800,...,-0.136195,0.657364,0.429852,0.399137,0.622330,0.448485,0.612637,0.533623,0.011501,0.130053
Connecticut,0.680886,0.047580,0.876215,0.402020,1.000000,0.552613,0.652488,0.487750,0.632073,0.621503,...,0.531769,0.626712,0.802485,0.105707,0.302538,0.898469,0.715691,0.400099,0.585790,0.814971
Delaware,0.258997,0.016125,0.479197,0.566304,0.552613,1.000000,0.796457,-0.009271,0.179312,0.466178,...,0.038750,0.427616,0.772410,0.318865,0.501815,0.487378,0.830850,0.436045,0.071042,0.502713
District of Columbia,0.321785,0.266889,0.596865,0.673371,0.652488,0.796457,1.000000,0.151129,0.335275,0.603762,...,0.159928,0.513618,0.820135,0.525490,0.537581,0.718686,0.798094,0.644477,0.267017,0.438793
Federal (FLSA),0.637679,0.117245,0.371966,-0.232035,0.487750,-0.009271,0.151129,1.000000,0.881708,0.472021,...,0.942402,0.011784,0.266963,0.098267,0.221539,0.504419,0.075067,0.272645,0.870658,0.328639
Guam,0.787915,0.039593,0.492052,-0.192616,0.632073,0.179312,0.335275,0.881708,1.000000,0.590844,...,0.814443,-0.002810,0.472814,-0.022460,0.098186,0.557049,0.223620,0.147441,0.738986,0.542694
Hawaii,0.672620,0.204801,0.519241,0.069800,0.621503,0.466178,0.603762,0.472021,0.590844,1.000000,...,0.517041,0.097491,0.741192,0.197210,0.099742,0.692043,0.500421,0.408709,0.599138,0.599665
Idaho,0.371515,-0.006833,0.623225,0.521063,0.563913,0.708405,0.671306,0.338621,0.410607,0.368091,...,0.336762,0.384715,0.608707,0.361028,0.843642,0.571039,0.792100,0.394586,0.376538,0.398222
Indiana,0.352950,-0.116454,0.793831,0.665580,0.731378,0.675197,0.664098,0.133628,0.262175,0.311292,...,0.169052,0.710746,0.676312,0.217810,0.662085,0.702334,0.884676,0.390353,0.272633,0.576864
Kentucky,-0.569134,0.427054,-0.152946,0.497117,-0.179488,0.200148,0.237560,-0.255126,-0.501651,-0.141714,...,-0.237805,0.414329,-0.006553,0.754947,0.547048,0.014395,0.167597,0.618312,-0.176467,-0.423665
Maine,0.784052,-0.059840,0.716943,0.100846,0.666562,0.173486,0.375888,0.622760,0.575916,0.716290,...,0.649450,0.184973,0.640188,0.051051,0.164233,0.814240,0.441776,0.353293,0.798669,0.581278
Maryland,0.487056,0.443650,0.377899,-0.044345,0.553702,0.039299,0.346281,0.880329,0.824104,0.517447,...,0.869714,0.178845,0.350190,0.369260,0.264487,0.579382,0.128251,0.479068,0.768901,0.271276
Massachusetts,0.726248,-0.136325,0.942760,0.469242,0.905269,0.537094,0.656305,0.416165,0.557130,0.604166,...,0.467695,0.508216,0.803758,-0.012230,0.341078,0.887631,0.729475,0.420851,0.587236,0.710190
Michigan,0.606292,0.113882,0.654850,0.184005,0.747738,0.142551,0.379898,0.737017,0.690024,0.487391,...,0.811266,0.410665,0.474120,0.094137,0.167255,0.753253,0.317154,0.503502,0.822971,0.534698
Minnesota,-0.384472,0.452996,-0.318507,-0.070367,-0.357928,-0.419871,-0.194168,0.034715,-0.281617,-0.181494,...,0.004847,-0.111083,-0.306054,0.456192,0.110139,-0.166611,-0.401047,0.309698,0.038940,-0.658956
Nebraska,-0.142350,0.180337,0.232873,0.736112,0.185571,0.752485,0.734443,-0.250411,-0.185862,0.199326,...,-0.247247,0.408780,0.512481,0.605302,0.627678,0.280478,0.616860,0.640071,-0.149191,0.017794
Nevada,0.713637,-0.005549,0.537317,0.085357,0.632557,0.559386,0.522322,0.759930,0.786231,0.679905,...,0.776806,0.104381,0.650662,0.156953,0.363154,0.631186,0.503730,0.384722,0.758705,0.553051
New Hampshire,0.817509,-0.192707,0.559870,-0.147020,0.544013,0.084726,0.186286,0.905728,0.848651,0.541385,...,0.881187,-0.051332,0.413565,-0.136714,0.154479,0.582379,0.196878,0.214541,0.887207,0.468841
New Jersey,0.726091,-0.093417,0.643447,0.045434,0.529780,0.185884,0.403857,0.640923,0.656598,0.702774,...,0.698329,0.035513,0.581925,0.019043,0.265946,0.693909,0.412325,0.395980,0.812427,0.436620
New Mexico,0.521504,0.042759,0.538274,0.213957,0.532646,0.205677,0.453302,0.610602,0.549588,0.633616,...,0.644610,0.303179,0.513619,0.220143,0.294331,0.710200,0.389211,0.605957,0.718676,0.454799
New York,0.881634,-0.236279,0.763132,0.002463,0.776332,0.291382,0.403779,0.640902,0.790776,0.651270,...,0.675860,0.174415,0.670161,-0.185229,0.058499,0.757560,0.473884,0.234554,0.713399,0.760379
North Carolina,0.454404,0.413676,0.450594,0.212403,0.629509,0.353903,0.528760,0.790967,0.717387,0.651703,...,0.820732,0.341955,0.492652,0.440417,0.444775,0.673769,0.370435,0.584352,0.798152,0.389918

In [20]:
for problem in issue_df['State'].unique():
    if problem in minimum_wage_corr.columns:
        print("We're missiong some data!!")

In [21]:
minimum_wage_corr

,Alaska,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Federal (FLSA),Guam,Hawaii,...,Pennsylvania,Puerto Rico,Rhode Island,South Dakota,Utah,Vermont,Washington,West Virginia,Wisconsin,Wyoming
Alaska,1.000000,-0.377934,0.717653,-0.129332,0.680886,0.258997,0.321785,0.637679,0.787915,0.672620,...,0.610814,-0.038118,0.652353,-0.326316,-0.020462,0.663558,0.411593,0.044814,0.702570,0.727932
Arkansas,-0.377934,1.000000,-0.234367,0.135749,0.047580,0.016125,0.266889,0.117245,0.039593,0.204801,...,0.159923,0.232186,0.003498,0.800116,0.194680,0.087429,-0.072343,0.420819,0.000470,-0.250592
California,0.717653,-0.234367,1.000000,0.483313,0.876215,0.479197,0.596865,0.371966,0.492052,0.519241,...,0.429061,0.512712,0.780916,-0.036787,0.392898,0.877922,0.754085,0.371765,0.584067,0.722617
Colorado,-0.129332,0.135749,0.483313,1.000000,0.402020,0.566304,0.673371,-0.232035,-0.192616,0.069800,...,-0.136195,0.657364,0.429852,0.399137,0.622330,0.448485,0.612637,0.533623,0.011501,0.130053
Connecticut,0.680886,0.047580,0.876215,0.402020,1.000000,0.552613,0.652488,0.487750,0.632073,0.621503,...,0.531769,0.626712,0.802485,0.105707,0.302538,0.898469,0.715691,0.400099,0.585790,0.814971
Delaware,0.258997,0.016125,0.479197,0.566304,0.552613,1.000000,0.796457,-0.009271,0.179312,0.466178,...,0.038750,0.427616,0.772410,0.318865,0.501815,0.487378,0.830850,0.436045,0.071042,0.502713
District of Columbia,0.321785,0.266889,0.596865,0.673371,0.652488,0.796457,1.000000,0.151129,0.335275,0.603762,...,0.159928,0.513618,0.820135,0.525490,0.537581,0.718686,0.798094,0.644477,0.267017,0.438793
Federal (FLSA),0.637679,0.117245,0.371966,-0.232035,0.487750,-0.009271,0.151129,1.000000,0.881708,0.472021,...,0.942402,0.011784,0.266963,0.098267,0.221539,0.504419,0.075067,0.272645,0.870658,0.328639
Guam,0.787915,0.039593,0.492052,-0.192616,0.632073,0.179312,0.335275,0.881708,1.000000,0.590844,...,0.814443,-0.002810,0.472814,-0.022460,0.098186,0.557049,0.223620,0.147441,0.738986,0.542694
Hawaii,0.672620,0.204801,0.519241,0.069800,0.621503,0.466178,0.603762,0.472021,0.590844,1.000000,...,0.517041,0.097491,0.741192,0.197210,0.099742,0.692043,0.500421,0.408709,0.599138,0.599665
Idaho,0.371515,-0.006833,0.623225,0.521063,0.563913,0.708405,0.671306,0.338621,0.410607,0.368091,...,0.336762,0.384715,0.608707,0.361028,0.843642,0.571039,0.792100,0.394586,0.376538,0.398222
Indiana,0.352950,-0.116454,0.793831,0.665580,0.731378,0.675197,0.664098,0.133628,0.262175,0.311292,...,0.169052,0.710746,0.676312,0.217810,0.662085,0.702334,0.884676,0.390353,0.272633,0.576864
Kentucky,-0.569134,0.427054,-0.152946,0.497117,-0.179488,0.200148,0.237560,-0.255126,-0.501651,-0.141714,...,-0.237805,0.414329,-0.006553,0.754947,0.547048,0.014395,0.167597,0.618312,-0.176467,-0.423665
Maine,0.784052,-0.059840,0.716943,0.100846,0.666562,0.173486,0.375888,0.622760,0.575916,0.716290,...,0.649450,0.184973,0.640188,0.051051,0.164233,0.814240,0.441776,0.353293,0.798669,0.581278
Maryland,0.487056,0.443650,0.377899,-0.044345,0.553702,0.039299,0.346281,0.880329,0.824104,0.517447,...,0.869714,0.178845,0.350190,0.369260,0.264487,0.579382,0.128251,0.479068,0.768901,0.271276
Massachusetts,0.726248,-0.136325,0.942760,0.469242,0.905269,0.537094,0.656305,0.416165,0.557130,0.604166,...,0.467695,0.508216,0.803758,-0.012230,0.341078,0.887631,0.729475,0.420851,0.587236,0.710190
Michigan,0.606292,0.113882,0.654850,0.184005,0.747738,0.142551,0.379898,0.737017,0.690024,0.487391,...,0.811266,0.410665,0.474120,0.094137,0.167255,0.753253,0.317154,0.503502,0.822971,0.534698
Minnesota,-0.384472,0.452996,-0.318507,-0.070367,-0.357928,-0.419871,-0.194168,0.034715,-0.281617,-0.181494,...,0.004847,-0.111083,-0.306054,0.456192,0.110139,-0.166611,-0.401047,0.309698,0.038940,-0.658956
Nebraska,-0.142350,0.180337,0.232873,0.736112,0.185571,0.752485,0.734443,-0.250411,-0.185862,0.199326,...,-0.247247,0.408780,0.512481,0.605302,0.627678,0.280478,0.616860,0.640071,-0.149191,0.017794
Nevada,0.713637,-0.005549,0.537317,0.085357,0.632557,0.559386,0.522322,0.759930,0.786231,0.679905,...,0.776806,0.104381,0.650662,0.156953,0.363154,0.631186,0.503730,0.384722,0.758705,0.553051
New Hampshire,0.817509,-0.192707,0.559870,-0.147020,0.544013,0.084726,0.186286,0.905728,0.848651,0.541385,...,0.881187,-0.051332,0.413565,-0.136714,0.154479,0.582379,0.196878,0.214541,0.887207,0.468841
New Jersey,0.726091,-0.093417,0.643447,0.045434,0.529780,0.185884,0.403857,0.640923,0.656598,0.702774,...,0.698329,0.035513,0.581925,0.019043,0.265946,0.693909,0.412325,0.395980,0.812427,0.436620
New Mexico,0.521504,0.042759,0.538274,0.213957,0.532646,0.205677,0.453302,0.610602,0.549588,0.633616,...,0.644610,0.303179,0.513619,0.220143,0.294331,0.710200,0.389211,0.605957,0.718676,0.454799
New York,0.881634,-0.236279,0.763132,0.002463,0.776332,0.291382,0.403779,0.640902,0.790776,0.651270,...,0.675860,0.174415,0.670161,-0.185229,0.058499,0.757560,0.473884,0.234554,0.713399,0.760379
North Carolina,0.454404,0.413676,0.450594,0.212403,0.629509,0.353903,0.528760,0.790967,0.717387,0.651703,...,0.820732,0.341955,0.492652,0.440417,0.444775,0.673769,0.370435,0.584352,0.798152,0.389918

In [22]:
grouped_issues = issue_df.groupby("State")

In [23]:
grouped_issues.get_group("Alabama")

,Unnamed: 0,Year,Table_Data,Footnote,High.Value,Low.Value,CPI.Average,High.2018,Low.2018
0,0,1968,...,NaN,0.0,0.0,34.783333,0.0,0.0
55,55,1969,...,NaN,0.0,0.0,36.683333,0.0,0.0
110,110,1970,...,NaN,0.0,0.0,38.825000,0.0,0.0
165,165,1971,...,NaN,0.0,0.0,40.491667,0.0,0.0
220,220,1972,...,NaN,0.0,0.0,41.816667,0.0,0.0
275,275,1973,...,NaN,0.0,0.0,44.400000,0.0,0.0
330,330,1974,...,NaN,0.0,0.0,49.308333,0.0,0.0
385,385,1975,...,NaN,0.0,0.0,53.816667,0.0,0.0
440,440,1976,...,NaN,0.0,0.0,56.908333,0.0,0.0
495,495,1977,...,NaN,0.0,0.0,60.608333,0.0,0.0
550,550,1978,...,NaN,0.0,0.0,65.233333,0.0,0.0
605,605,1979,...,NaN,0.0,0.0,72.575000,0.0,0.0
660,660,1980,...,NaN,0.0,0.0,82.408333,0.0,0.0
715,715,1981,...,NaN,0.0,0.0,90.925000,0.0,0.0
770,770,1982,...,NaN,0.0,0.0,96.500000,0.0,0.0
825,825,1983,...,NaN,0.0,0.0,99.600000,0.0,0.0
880,880,1984,...,NaN,0.0,0.0,103.883333,0.0,0.0
935,935,1985,...,NaN,0.0,0.0,107.566667,0.0,0.0
990,990,1986,...,NaN,0.0,0.0,109.608333,0.0,0.0
1045,1045,1987,...,NaN,0.0,0.0,113.625000,0.0,0.0
1100,1100,1988,...,NaN,0.0,0.0,118.258333,0.0,0.0
1155,1155,1989,...,NaN,0.0,0.0,123.966667,0.0,0.0
1210,1210,1990,...,NaN,0.0,0.0,130.658333,0.0,0.0
1265,1265,1991,...,NaN,0.0,0.0,136.191667,0.0,0.0
1320,1320,1992,...,NaN,0.0,0.0,140.316667,0.0,0.0
1375,1375,1993,...,NaN,0.0,0.0,144.458333,0.0,0.0
1430,1430,1994,...,NaN,0.0,0.0,148.225000,0.0,0.0
1485,1485,1995,...,NaN,0.0,0.0,152.383333,0.0,0.0
1540,1540,1996,...,NaN,0.0,0.0,156.850000,0.0,0.0
1595,1595,1997,...,NaN,0.0,0.0,160.516667,0.0,0.0
1650,1650,1998,...,NaN,0.0,0.0,163.008333,0.0,0.0
1705,1705,1999,...,NaN,0.0,0.0,166.575000,0.0,0.0
1760,1760,2000,...,NaN,0.0,0.0,172.200000,0.0,0.0
1815,1815,2001,...,NaN,0.0,0.0,177.066667,0.0,0.0
1870,1870,2002,...,NaN,0.0,0.0,179.875000,0.0,0.0
1925,1925,2003,...,NaN,0.0,0.0,183.958333,0.0,0.0
1980,1980,2004,...,NaN,0.0,0.0,188.883333,0.0,0.0
2035,2035,2005,...,NaN,0.0,0.0,195.291667,0.0,0.0
2090,2090,2006,...,NaN,0.0,0.0,201.591667,0.0,0.0
2145,2145,2007,...,NaN,0.0,0.0,207.342417,0.0,0.0
2200,2200,2008,...,NaN,0.0,0.0,215.302500,0.0,0.0
2255,2255,2009,...,NaN,0.0,0.0,214.537000,0.0,0.0
2310,2310,2010,...,NaN,0.0,0.0,218.055500,0.0,0.0
2365,2365,2011,...,NaN,0.0,0.0,224.939167,0.0,0.0
2420,2420,2012,...,NaN,0.0,0.0,229.593917,0.0,0.0
2475,2475,2013,...,NaN,0.0,0.0,232.957083,0.0,0.0
2530,2530,2014,...,NaN,0.0,0.0,236.736167,0.0,0.0
2585,2585,2015,...,NaN,0.0,0.0,237.017000,0.0,0.0
2640,2640,2016,...,NaN,0.0,0.0,240.007167,0.0,0.0
2695,2695,2017,...,NaN,0.0,0.0,245.119583,0.0,0.0

In [33]:
grouped_issues.get_group("Florida")["Low.2018"].sum()

0.0

In [25]:
grouped_issues.get_group("Alabama")["Low.2018"].sum()

0.0

In [27]:
for state, data in grouped_issues:
    if data['Low.2018'].sum()!=0:
        print("Some data found in", state)

In [34]:
grouped_issues["State"].unique()

State
Alabama                  [Alabama]
Arizona                  [Arizona]
Florida                  [Florida]
Georgia                  [Georgia]
Illinois                [Illinois]
Iowa                        [Iowa]
Kansas                    [Kansas]
Louisiana              [Louisiana]
Mississippi          [Mississippi]
Missouri                [Missouri]
Montana                  [Montana]
South Carolina    [South Carolina]
Tennessee              [Tennessee]
Texas                      [Texas]
Virginia                [Virginia]
Name: State, dtype: object